/*
 * Brain4it
 *
 * Copyright (C) 2018, Ajuntament de Sant Feliu de Llobregat
 *
 * This program is licensed and may be used, modified and redistributed under
 * the terms of the European Public License (EUPL), either version 1.1 or (at
 * your option) any later version as soon as they are approved by the European
 * Commission.
 *
 * Alternatively, you may redistribute and/or modify this program under the
 * terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either  version 3 of the License, or (at your option)
 * any later version.
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the licenses for the specific language governing permissions, limitations
 * and more details.
 *
 * You should have received a copy of the EUPL1.1 and the LGPLv3 licenses along
 * with this program; if not, you may find them at:
 *
 *   https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 *   http://www.gnu.org/licenses/
 *   and
 *   https://www.gnu.org/licenses/lgpl.txt
 */

package org.brain4it.manager.swing;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Properties;
import java.util.ResourceBundle;
import javax.swing.table.DefaultTableModel;
import org.brain4it.version.VersionInfo;

/**
 *
 * @author realor
 */
public class AboutDialog extends javax.swing.JDialog
{
  public AboutDialog(ManagerApp managerApp, boolean modal)
  {
    super(managerApp, modal);
    initComponents();
    initDialog();
    loadProperties();
  }

  private void initDialog()
  {
    creditsLabel.setText(VersionInfo.CREDITS);
    int scalingFactor = ManagerApp.getPreferences().getScalingFactor();
    propertiesTable.setRowHeight(20 * scalingFactor);

    ResourceBundle bundle = ResourceBundle.getBundle(
      "org/brain4it/manager/swing/resources/Manager");
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("Property");
    model.addColumn("Value");
    propertiesTable.getTableHeader().setReorderingAllowed(false);
    propertiesTable.setModel(model);
    propertiesTable.getColumnModel().getColumn(0).
      setHeaderValue(bundle.getString("About.property"));
    propertiesTable.getColumnModel().getColumn(1).
      setHeaderValue(bundle.getString("About.value"));

    String versionString = VersionInfo.getVersionString();
    if (versionString != null)
    {
      versionLabel.setText(versionString);
    }
  }

  private void loadProperties()
  {
    Properties properties = System.getProperties();
    ArrayList<String> names = new ArrayList<String>();
    names.addAll(properties.stringPropertyNames());
    Collections.sort(names);
    for (String name : names)
    {
      ((DefaultTableModel)propertiesTable.getModel()).addRow(new Object[]
      {name, String.valueOf(properties.get(name))});
    }
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    logoPanel = new javax.swing.JPanel();
    logoLabel = new javax.swing.JLabel();
    infoPanel = new javax.swing.JPanel();
    versionLabel = new javax.swing.JLabel();
    creditsLabel = new javax.swing.JLabel();
    propertiesScrollPane = new javax.swing.JScrollPane();
    propertiesTable = new javax.swing.JTable();
    southPanel = new javax.swing.JPanel();
    okButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("org/brain4it/manager/swing/resources/Manager"); // NOI18N
    setTitle(bundle.getString("About")); // NOI18N

    logoPanel.setBackground(new java.awt.Color(255, 255, 255));
    logoPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    logoPanel.setLayout(new java.awt.BorderLayout());

    logoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    logoLabel.setIcon(IconCache.getIcon("brain4it"));
    logoPanel.add(logoLabel, java.awt.BorderLayout.CENTER);

    infoPanel.setOpaque(false);
    infoPanel.setLayout(new java.awt.BorderLayout());

    versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    versionLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 1, 4, 1));
    infoPanel.add(versionLabel, java.awt.BorderLayout.CENTER);
    versionLabel.getAccessibleContext().setAccessibleName("version");

    creditsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    creditsLabel.setText("Credits");
    infoPanel.add(creditsLabel, java.awt.BorderLayout.SOUTH);
    creditsLabel.getAccessibleContext().setAccessibleName("creditsLabel");

    logoPanel.add(infoPanel, java.awt.BorderLayout.SOUTH);

    getContentPane().add(logoPanel, java.awt.BorderLayout.NORTH);

    propertiesTable.setAutoCreateRowSorter(true);
    propertiesTable.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][]
      {

      },
      new String []
      {

      }
    ));
    propertiesScrollPane.setViewportView(propertiesTable);

    getContentPane().add(propertiesScrollPane, java.awt.BorderLayout.CENTER);

    okButton.setText(bundle.getString("Accept")); // NOI18N
    okButton.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        okButtonActionPerformed(evt);
      }
    });
    southPanel.add(okButton);

    getContentPane().add(southPanel, java.awt.BorderLayout.PAGE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okButtonActionPerformed
  {//GEN-HEADEREND:event_okButtonActionPerformed
    setVisible(false);
    dispose();
  }//GEN-LAST:event_okButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel creditsLabel;
  private javax.swing.JPanel infoPanel;
  private javax.swing.JLabel logoLabel;
  private javax.swing.JPanel logoPanel;
  private javax.swing.JButton okButton;
  private javax.swing.JScrollPane propertiesScrollPane;
  private javax.swing.JTable propertiesTable;
  private javax.swing.JPanel southPanel;
  private javax.swing.JLabel versionLabel;
  // End of variables declaration//GEN-END:variables

}
