/*
 * Brain4it
 * 
 * Copyright (C) 2018, Ajuntament de Sant Feliu de Llobregat
 * 
 * This program is licensed and may be used, modified and redistributed under 
 * the terms of the European Public License (EUPL), either version 1.1 or (at 
 * your option) any later version as soon as they are approved by the European 
 * Commission.
 * 
 * Alternatively, you may redistribute and/or modify this program under the 
 * terms of the GNU Lesser General Public License as published by the Free 
 * Software Foundation; either  version 3 of the License, or (at your option) 
 * any later version. 
 *   
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT 
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 *   
 * See the licenses for the specific language governing permissions, limitations 
 * and more details.
 *   
 * You should have received a copy of the EUPL1.1 and the LGPLv3 licenses along 
 * with this program; if not, you may find them at: 
 *   
 *   https://joinup.ec.europa.eu/software/page/eupl/licence-eupl
 *   http://www.gnu.org/licenses/ 
 *   and 
 *   https://www.gnu.org/licenses/lgpl.txt
 */
package org.brain4it.manager.swing;

/**
 *
 * @author realor
 */
public class DesignerAuxiliaryPanel extends javax.swing.JPanel
{
  /**
   * Creates new form DesignerAuxiliaryPanel
   */
  public DesignerAuxiliaryPanel()
  {
    initComponents();
  }

  public Palette getPalette()
  {
    return palette;
  }
  
  public DashboardWidgetEditor getDashboardWidgetEditor()
  {
    return widgetEditor;
  }
  
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    splitPane = new javax.swing.JSplitPane();
    palette = new org.brain4it.manager.swing.Palette();
    widgetEditor = new org.brain4it.manager.swing.DashboardWidgetEditor();

    setLayout(new java.awt.BorderLayout());

    splitPane.setBorder(null);
    splitPane.setDividerLocation(200);
    splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
    splitPane.setLeftComponent(palette);
    splitPane.setRightComponent(widgetEditor);

    add(splitPane, java.awt.BorderLayout.CENTER);
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private org.brain4it.manager.swing.Palette palette;
  private javax.swing.JSplitPane splitPane;
  private org.brain4it.manager.swing.DashboardWidgetEditor widgetEditor;
  // End of variables declaration//GEN-END:variables
}
